# Generated by Django 3.2.15 on 2024-09-07 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240123_0902'),
        ('service', '0004_auto_20240906_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='users.profile'),
            preserve_default=False,
        ),
    ]
