# Generated by Django 3.2.15 on 2024-09-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_supplier_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='category',
        ),
    ]
